---
title: "demographics scatterplots"
author: "Linnea Powell"
date: "June 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE}
library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(plotly)
```

```{r}
dem <- readRDS( gzcon(url("https://github.com/USAspendingexplorer/USAspending-explorer/blob/master/Data/Processed/NYcensus.rds?raw=true")))

# select only necessary columns
dem2 <-select(dem, county.name, Pop, MHincome, pov.rate)

#dem2.1 <- mutate(dem2, pov.rate = paste(round(100*pov.rate, 1), "%", sep=""))

#dem2.1.1 <- mutate(dem2.1, MHincome = paste("$",format(MHincome, big.mark=","),sep=""))


```


```{r}
hovertxt <- paste( "County:", dem2$county.name
                   , "
                   "
                   , "Population:", prettyNum( dem2$Pop
                                               , big.mark = ","
                                               , preserve.width = "none"
                                               )
                             )

plot_ly(data = dem2, x = ~county.name, y = ~Pop, name = "",
        marker = list(color = "#F67670", size = 7))%>%
add_markers(hoverinfo="text", text=hovertxt) %>%
layout(xaxis = list(title = 'County', showticklabels=FALSE, showgrid=FALSE),
      yaxis = list(title = 'Population', showgrid=FALSE))
```


```{r}
library(scales)
hovertxt2 <- paste("County:",dem2$county.name, "
", "Median Household Income:", dollar( dem2$MHincome ) )

plot_ly(data = dem2, x = ~county.name, y = ~MHincome, name = "",
        marker = list(color = "#1BB841", size = 7))%>%
add_markers(hoverinfo="text", text=hovertxt2) %>%
layout(xaxis = list(title = 'County', showticklabels=FALSE, showgrid=FALSE),
      yaxis = list(title = 'Median Household Income', showgrid=FALSE, showticklabels=TRUE))


```


```{r}
hovertxt3 <- paste("County:",dem2$county.name, "
", "Poverty Rate:", paste(round(100*dem2$pov.rate, 1)
                          , "%"
                          , sep=""
                          )
)

plot_ly(data = dem2, x = ~county.name, y = ~pov.rate, name = "",
        marker = list(color = "#649EFC", size = 7)) %>%
add_markers(hoverinfo="text", text=hovertxt3) %>%
layout(xaxis = list(title = 'County', showticklabels=FALSE, showgrid=FALSE),
      yaxis =list(title = 'Poverty Rate', showgrid=FALSE, showticklabels=TRUE))


```

```{r}
hovertxt4 <- paste("County:",dem2$county.name, "
", "Poverty Rate:", paste(round(100*dem2$pov.rate, 1)
                          , "%"
                          , sep=""
                          )
, "
", "Median HH Income:", dollar( dem2$MHincome )
)




plot_ly(data = dem2, x = ~MHincome, y = ~pov.rate, name = "",
        marker = list(color = "#A58AFF", size = 7)) %>%
add_markers(hoverinfo="text", text=hovertxt4) %>%
layout(xaxis = list(title = 'Median Household Income', showticklabels=TRUE, showgrid=FALSE),
      yaxis =list(title = 'Poverty Rate', showgrid=FALSE, showticklabels=TRUE))
```

```{r}
hovertxt5 <- paste("County:",dem2$county.name, "
", "Poverty Rate:", paste(round(100*dem2$pov.rate, 1)
                          , "%"
                          , sep=""
                          )
, "
", "Population:", prettyNum( dem2$Pop
                                  , big.mark = ","
                                  , preserve.width = "none"
                                   )
)




plot_ly(data = dem2, x = ~Pop, y = ~pov.rate, name = "",
        marker = list(color = "#00C19F", size = 7)) %>%
add_markers(hoverinfo="text", text=hovertxt5) %>%
layout(xaxis = list(title = 'Population', showticklabels=TRUE, showgrid=FALSE),
      yaxis =list(title = 'Poverty Rate', showgrid=FALSE, showticklabels=TRUE))
```

```{r}
hovertxt6 <- paste("County:",dem2$county.name, "
", "Median HH Income:", dollar( dem2$MHincome )
, "
", "Population:", prettyNum( dem2$Pop
                                  , big.mark = ","
                                  , preserve.width = "none"
                                   )
)




plot_ly(data = dem2, x = ~MHincome, y = ~Pop, name = "",
        marker = list(color = "#A3A500", size = 7)) %>%
add_markers(hoverinfo="text", text=hovertxt6) %>%
layout(xaxis = list(title = 'Median Household Income', showticklabels=TRUE, showgrid=FALSE),
      yaxis =list(title = 'Population', showgrid=FALSE, showticklabels=TRUE))
```

