---
title: "Matching Counties"
output: github_document
html_document:
  df_print: paged
  keep_md: true
  code_fold: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = T, message=F, warning=F, fig.width = 10, fig.height = 10 )
library(censusapi)
library(dplyr)
library(pander)
library(geojsonio)
library(sp) #need this to read the json shapes in gplot
#install.packages("MatchIt")
library(MatchIt)

setwd("C:/Users/icps/Dropbox/3. Maxwell/4. Capston")

```

```{r}

#loading the census DF
dem <- readRDS( gzcon(url("https://github.com/USAspendingexplorer/USAspending-explorer/blob/master/Data/Processed/NYcensus.rds?raw=true")))

#loading the match function
url <- "https://raw.githubusercontent.com/USAspendingexplorer/USAspending-explorer/master/Build%20App/matching_function.R"
source_github(url)


#### A COPY OF THE FUNCTION TO WORK WITH ####
x<-dem
county <- "Kings"
comparators <- 2

krzymatch <- function(x, county= "Albany", comparators= 2) 
{
  # Load Required Packages
  require(MatchIt)  
  
  #assigning the selected county into the treatment group
  tmp <- x$county.name == county
  x$Treat <- 0
  x$Treat[tmp] <- 1
  
  #creating objects
  lis <- rep(NA,comparators)
  dis <- c(rep(FALSE, 62), TRUE)
  
  #loop to find the top comparatos
  for (i in c(1:comparators)) 
  {
    mat <- matchit(x$Treat ~  Pop + pov.rate, data = dat, discard = dis)
    tmp <- as.numeric(mat$match.matrix)
    dis[tmp] <- TRUE
    lis[i] <- as.character(x$county.name[tmp])
  }
  return(lis)
}


list<- krzymatch(dem, "Onondaga", 3)

class(list)


#TRYING TO SEE THE DIFFERENT OUTPUTS


#mat <- matchit(Treat ~  Pop + pov.rate, data = dat, discard = dis)
#"Matches for Tompkins: 1.Cattaraugus, 2.Chautauqua, 3.Oswego, 4.St. Lawrence, 5.Fulton"
#poverty rate is the most simliar

#mat <- matchit(Treat ~  pov.rate + Pop, data = dat, discard = dis)
#"Matches for Tompkins: 1.Sullivan, 2.Franklin, 3.Chenango, 4.Steuben, 5.Broome"
#wierd, again poverty is the one with most simlarity


#mat <- matchit(Treat ~  Pop, data = dat, discard = dis)
#"Matches for Tompkins: 1.Putnam, 2.Ontario, 3.Wayne, 4.Jefferson, 5.Chemung"
#efectively shows the simlarity.

```




